---
- hosts: all
  become: yes
  gather_facts: no
  tasks:
    - apt: upgrade=safe update_cache=true
    - apt: name={{item}} state=present install_recommends=no force=true
      with_items:
        - git
        - curl
        - libreadline-dev
        - build-essential
        - libmysqlclient-dev
        - libssl-dev
